# Generated by Django 2.2.1 on 2019-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
    ]
