# Generated by Django 2.2.1 on 2019-05-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True, verbose_name='business address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='business phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(max_length=50, null=True, verbose_name='website'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=100, null=True, verbose_name='partner name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='last name'),
        ),
    ]
