# Generated by Django 2.2.1 on 2019-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190525_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=50, null=True, verbose_name='verification code'),
        ),
    ]
