# Generated by Django 2.2.1 on 2019-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default='single', max_length=75, verbose_name='short description'),
            preserve_default=False,
        ),
    ]
