# Generated by Django 2.2.1 on 2019-05-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190522_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='street line 2'),
        ),
    ]
