# Generated by Django 2.2.1 on 2019-05-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190522_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('event', 'name')},
        ),
    ]
