# Generated by Django 2.2.1 on 2019-05-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190528_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Be clear and descriptive', max_length=100, verbose_name='title'),
        ),
    ]
