# Generated by Django 2.2.1 on 2019-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190528_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='qty'),
        ),
    ]
