# Generated by Django 2.2.1 on 2019-05-07 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('percentage', models.IntegerField(null=True, verbose_name='percentage')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
