# Generated by Django 2.2.1 on 2019-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20190507_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='percentage'),
        ),
    ]
