# Generated by Django 2.2.1 on 2019-05-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20190507_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounts',
            options={'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
    ]
