# Generated by Django 2.2.1 on 2019-05-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='options',
        ),
        migrations.AlterField(
            model_name='dealcategories',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='deals.Deals'),
        ),
    ]
