# Generated by Django 2.2.1 on 2019-05-05 08:20

import deals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20190504_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcategories',
            name='image',
            field=models.ImageField(upload_to=deals.models.deals_image_path, verbose_name='image'),
        ),
    ]
