# Generated by Django 2.2.1 on 2019-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20190505_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcategories',
            name='available_quantity',
            field=models.IntegerField(null=True, verbose_name='available quantity'),
        ),
    ]
