# Generated by Django 2.2.1 on 2019-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20190506_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'deal', 'verbose_name_plural': 'deals'},
        ),
        migrations.AlterField(
            model_name='dealcategories',
            name='available_quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='available quantity'),
        ),
    ]
