# Generated by Django 2.2.1 on 2019-05-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20190522_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='deals.Categories'),
        ),
    ]
