# Generated by Django 2.2.1 on 2019-05-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20190524_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Categories'),
        ),
    ]
