# Generated by Django 2.2.1 on 2019-06-10 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20190610_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
    ]
