# Generated by Django 2.2.1 on 2019-05-07 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('start_date_time', models.DateTimeField(verbose_name='from')),
                ('end_date_time', models.DateTimeField(verbose_name='to')),
                ('budget_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='from')),
                ('budget_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='to')),
                ('engagement_scope', models.TextField(verbose_name='engagement scope')),
                ('venue', models.TextField(verbose_name='venue')),
                ('other_details', models.TextField(blank=True, verbose_name='other details')),
                ('resolution', models.TextField(default=None, null=True, verbose_name='resolved?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingTalents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('industry', models.CharField(max_length=100, verbose_name='industry')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talents', to='talents.Bookings')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
