# Generated by Django 2.2.1 on 2019-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_auto_20190514_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingtalents',
            options={'verbose_name_plural': 'booking talents'},
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='resolution',
        ),
        migrations.AddField(
            model_name='bookings',
            name='is_resolved',
            field=models.TextField(default=None, null=True, verbose_name='is resolved'),
        ),
    ]
