# Generated by Django 2.2.1 on 2019-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_auto_20190515_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='is_resolved',
            field=models.TextField(default=False, verbose_name='is resolved'),
        ),
    ]
