# Generated by Django 2.2.1 on 2019-05-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0005_auto_20190515_1003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingtalents',
            options={'verbose_name': 'booking talent', 'verbose_name_plural': 'booking talents'},
        ),
    ]
