# Generated by Django 2.2.1 on 2019-06-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0007_auto_20190604_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='industry'),
        ),
    ]
