# Generated by Django 2.2.1 on 2019-06-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_auto_20190609_2305'),
        ('talents', '0008_auto_20190610_1148'),
    ]

    operations = [
    ]
