# Generated by Django 2.2.1 on 2019-06-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0009_merge_20190611_0951'),
        ('talents', '0009_merge_20190611_0952'),
    ]

    operations = [
    ]
