# Generated by Django 2.2.1 on 2019-06-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='state',
            field=models.CharField(default='Lagos', max_length=100, verbose_name='state'),
            preserve_default=False,
        ),
    ]
